apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  port:
    targetPort: http
  wildcardPolicy: None
  to:
    kind: Service
    name: {{ include "app.fullname" . }}
    weight: 100
